#!/bin/sh
    
pushd lib
libtool -o libspatialiteall.a *.a
popd
pushd build/arm64-ios/lib
libtool -o libspatialiteall.a *.a
popd

# Make framework
xcodebuild -create-xcframework -library lib/libspatialiteall.a -headers include/ -library build/arm64-ios/lib/libspatialiteall.a -headers include/ -output libspatialite.xcframework
