#!/bin/sh
    
pushd build/arm64-ios/lib
libtool -o libspatialiteall.a *.a
popd
pushd build/arm64-sim/lib
libtool -o libspatialiteall.a *.a
popd

# Make framework
xcodebuild -create-xcframework \
	-library build/arm64-ios/lib/libspatialiteall.a \
	-headers include/ \
	-library build/arm64-sim/lib/libspatialiteall.a \
	-headers include/ \
	-output libspatialite.xcframework
